# Generated by Django 3.2.8 on 2021-10-06 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(default=0)),
                ('contacted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('YT', 'Youtube'), ('G', 'Google'), ('NL', 'Newsletter')], default='YT', max_length=2)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=leads.models.profile_pic)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.agent')),
            ],
        ),
    ]
