# Generated by Django 3.2.8 on 2021-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(default='sadddddddddddddddddddddddddddllllllllllllllllllllllllllllllllllllllllllddddddddddddddooooooooooooooooooooooooooooooooooooqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqppppppppppppppppppppppppppppppppppp2222222222222222222222222222222222222222222222222222222222222222222222222222222222'),
            preserve_default=False,
        ),
    ]
