# Generated by Django 3.2.8 on 2021-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cell_phone',
            field=models.CharField(default='+91 548752644', max_length=20),
            preserve_default=False,
        ),
    ]
