# Generated by Django 3.2.8 on 2021-10-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211008_1846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('is_agent_manager', 'is_agent')},
        ),
    ]
